safe: true
lsi: false
highlighter: pygments
markdown: kramdown

baseurl: http://andystaging.rwlabs.org

collections:
  rwlabs:
    output: true
  challenge:
    output: true
  community:
    output: true
