safe: true
lsi: false
highlighter: rouge
markdown: kramdown

# https://help.github.com/articles/redirects-on-github-pages/
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

collections:
  projects:
    output: true
  decommissioned:
    output: false
